# Questão 2
Nessa próxima questão temos que fazer algo parecido com a primeira questão mas ao
invés de fazer com o enpoint do PUT nos usamos o do DELETE.

Temos esse endpoint:
```py
@app.delete('/users/{user_id}', response_model=Message)
def delete_user(user_id: int):
    if user_id > len(database) or user_id < 1:
        raise HTTPException(status_code=404, detail='User not found')

    del database[user_id - 1]

    return {'message': 'User deleted'}
```

Para testamos o exceção vou usar dessa vez um `user_id` maior que o tamanho do
nosso banco de dados falso, dessa forma:
```py
def test_error_delete_user_index_out_of_range(client):
    response = client.delete('/users/4')

    assert response.status_code == 404
    assert response.json() == {'detail': 'User not found'}
```

Com isso nosso código tem 100% de coverage.

